---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  - name: debian12
    box: generic/debian12
    memory: 2048
    cpus: 1

provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks

lint: |
  set -e
  ansible-lint

verifier:
  name: ansible
